### ISSUE TITLE
Express 프로젝트 생성 및 구조 설정

### ISSUE THREAD

**Issue by slogup-mia** [boostcamp-2020/IssueTracker-12#6]

**Comment by j03y14** [comment]
현재 web-BE-init 브랜치에 express, dotenv, nodemon, eslint를 설치해서 push 해놨습니다.
eslint는 `airbnb` 스타일로 하게 했습니다. app.js 파일을 만들어놨고 포트 번호는 `3000`번으로 해놨습니다.
