### ISSUE TITLE
FE 환경 빌드

### ISSUE THREAD

**Issue by slogup-mia** [boostcamp-2020/IssueTracker-12#64]
- [x] React Project Build
  - react-dom
  - react-router-dom
- [x] Web-pack
- [x] Barbel
- [x] ESlint

**Comment by safience-mia** [comment]
#### Pair Programing 신청합니다 😄 
> @j03y14 @SeunghyoKu 
- 해당 이슈는 다들 처음해보는거라 같이 해봤으면 좋겠어요.
- 세명이 다 해도 좋을 것 같아요
- 원래 주말이나 월요일에 제가 하려고 했는데 
- 급하게 진행하지 않고, 같이 학습하면 좋겠다 생각합니다 ~~~

**Comment by SeunghyoKu** [comment]
> #### Pair Programing 신청합니다 😄
> > @j03y14 @SeunghyoKu
> 
> * 해당 이슈는 다들 처음해보는거라 같이 해봤으면 좋겠어요.
> * 세명이 다 해도 좋을 것 같아요
> * 원래 주말이나 월요일에 제가 하려고 했는데
> * 급하게 진행하지 않고, 같이 학습하면 좋겠다 생각합니다 ~~~

좋아요! 언제가 좋으신가요? 👀
처음 하는 거다 보니 수원님 말씀대로 3명이서 하면 더  좋을 거 같아요!

**Comment by safience-mia** [comment]
> > #### Pair Programing 신청합니다 😄
> > > @j03y14 @SeunghyoKu
> > 
> > 
> > 
> > * 해당 이슈는 다들 처음해보는거라 같이 해봤으면 좋겠어요.
> > * 세명이 다 해도 좋을 것 같아요
> > * 원래 주말이나 월요일에 제가 하려고 했는데
> > * 급하게 진행하지 않고, 같이 학습하면 좋겠다 생각합니다 ~~~
> 
> 좋아요! 언제가 좋으신가요? 👀
> 처음 하는 거다 보니 수원님 말씀대로 3명이서 하면 더 좋을 거 같아요!

다음주 웹팀 회의 때 얘기해보아요! 
즐거운 주말 보내십셔~~~ 🏖
